### ISSUE TITLE
"File not found" when file name contains space

### ISSUE THREAD

**Issue by hordesalik** [Evolution-36/cordova-plugin-file-opener2#1]
When I'm trying to open a file with name containing " " charachter - "File not found" error appears

**Comment by Langstra** [comment]
What device and version of Android are you using?

**Comment by hordesalik** [comment]
Nokia 3, Android 8.0. Note: " " charachter is a "space"

**Comment by Langstra** [comment]
Could you try using ```var filePath = decodeURIComponent(filePath)``` and then use filePath to open the file?

**Comment by hordesalik** [comment]
It works. Thanks.
