### ISSUE TITLE
I am Not Good in Java So Please Tell me How to Use 

### ISSUE THREAD

**Issue by khan404** [Evolution-36/cordova-plugin-file-opener2#2]
Hy!
   I am New in Cordova Tell How to Use Cordova Plugin in index.html How to Call Funcation . I am Call PDF file Open In External App So please Help Me

**Comment by Langstra** [comment]
The README has detailed description on how to call the plugin using JavaScript. If you do not know how to use Cordova then please use the Cordova documentation.
